# Generated by Django 2.2.6 on 2019-11-02 20:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['tournament__pk', 'level'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['pk'], 'verbose_name': 'Tournament', 'verbose_name_plural': 'Tournaments'},
        ),
        migrations.AlterField(
            model_name='match',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='matches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_for_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='registered_users',
            field=models.ManyToManyField(blank=True, related_name='tournaments', to=settings.AUTH_USER_MODEL),
        ),
    ]
