# Generated by Django 2.2.6 on 2019-11-25 22:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20191125_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='time',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(),
        ),
    ]
