# Generated by Django 2.2.6 on 2020-03-03 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tm_manager_backend.tournament.utils.validators


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0004_auto_20191125_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['tournament__pk', '-level', 'id'], 'verbose_name': 'Match', 'verbose_name_plural': 'Matches'},
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'get_latest_by': 'id', 'ordering': ['-created', '-pk'], 'verbose_name': 'Tournament', 'verbose_name_plural': 'Tournaments'},
        ),
        migrations.AddField(
            model_name='tournament',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='won_tournaments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(validators=[tm_manager_backend.tournament.utils.validators.validate_date]),
        ),
    ]
